version: 0.2
phases:
  pre-build:
    - echo "This is the pre-build phases"
  build:
    commands:
      - echo "This is the build phases"
      - mvn clean prepare-package war:explode
  post-build:
    commands:
      - echo "This is the post-build phases"
      - mv target/deploy ./
artifacts:
  files:
    - deploy/**/*


